In [ ]:
import numpy as np


 https://www.kaggle.com/mjbahmani/the-data-scientist-s-toolbox-tutorial-2/

In [ ]:
m = np.array([[7,8,9],[10,11,12]])
m

In [98]:
m.shape

(2, 3)

In [ ]:


n = np.arange(0, 30, 60) # start at 0 count up by 2, stop before 30
n



In [ ]:
o = np.linspace(0,4,9)
k=o.reshape(3,3)
p = np.linspace(0,4,9)
p.resize(3,3)
k
#linspace returns evenly spaced numbers over a specified interval.

In [ ]:
np.ones((3,2))

In [ ]:
np.zeros((3,2))

In [ ]:
np.eye(3)
#returns a 2-D array with ones on the diagonal and zeros elsewhere.#特征值为1的n阶特征矩阵

In [ ]:
y=[4,5,6,7]
y= np.linspace(0,4,9)
np.diag(y)
#extracts a diagonal or constructs a diagonal array.特征矩阵

In [ ]:
np.array([1,2,3]*3)
#Create an array using repeating list

np.tile([1,2,3],[3,3])
#np.tile()将原矩阵横向纵向复制，也就是铺瓷砖一样

In [ ]:
np.repeat([1,2,3,1],5)
#Repeat elements of an array using repeat.

In [71]:
p = np.ones([4, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [72]:
np.vstack([p,2*p])
#Use vstack to stack arrays in sequence vertically (row wise).


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [73]:
np.hstack([p,2*p])
#Use hstack to stack arrays in sequence horizontally (column wise).


array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [118]:
x=np.array([1,2,3]) 
print(x.shape)
y=np.arange(4,7,1)
print(y)
y=np.resize(y,(3,1))
print(y)
print(y.shape)

print(x.dot(y))
x.dot(y)

(3,)
[4 5 6]
[[4]
 [5]
 [6]]
(3, 1)
[32]


array([32])

In [120]:
z = np.array([y,y**2])
print(len(z))

2
