In [6]:
import csv
import pandas as pd
import numpy as np

with open('house-prices-advanced-regression-techniques/train.csv') as csvfile:
    house_train = list(csv.DictReader(csvfile))
df = pd.read_csv('house-prices-advanced-regression-techniques/train.csv')
df[1:3]

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  

[2 rows x 81 columns]

In [15]:
sum(float(d['SalePrice']) for d in house_train)/len(house_train)

180921.19589041095

In [25]:
sum(df.SalePrice)/len(df)

180921.19589041095

In [32]:
SalePrice = set(d['SalePrice'] for d in house_train)
print(len(SalePrice))
SalePriceDedup = df.drop_duplicates(subset='SalePrice')
print(len(SalePriceDedup))

663
663


In [40]:
type(house_train[0])
type(df.iloc[1])

pandas.core.series.Series

In [60]:
import datetime as dt
import time as tm
time=tm.time()
dtnow = dt.datetime.fromtimestamp(tm.time())
delta = dt.timedelta(hours = 3)


datetime.timedelta(seconds=10800)

In [69]:
my_fuc = lambda x: x%2 -1 
result = list(filter(my_fuc, range(0,10)))
print(result)
my_list = [number for number in range(0,10) if number%2 == 0]


[0, 2, 4, 6, 8]


In [71]:
sorted(["a","abd",'dfiwo',"dw"],key = lambda x:len(x))

['a', 'dw', 'abd', 'dfiwo']

In [7]:
df = pd.DataFrame({"age":[21,3],
                  "name":['Eric','jason']})

In [14]:
pds = iter(df.age)

In [17]:
next(pds)

StopIteration: 

In [38]:
m = np.array([[3,4,5],[10,11,12]])
n = np.arange(0,60,1)
o = np.linspace(0,5,16)
k = o.reshape(2,2,2,2)
k


array([[[[0.        , 0.33333333],
         [0.66666667, 1.        ]],

        [[1.33333333, 1.66666667],
         [2.        , 2.33333333]]],


       [[[2.66666667, 3.        ],
         [3.33333333, 3.66666667]],

        [[4.        , 4.33333333],
         [4.66666667, 5.        ]]]])

In [50]:
k=np.ones((3,3,3,3))
k = np.zeros((3,3))
k

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
y = [4,5,6,7]
z=[1,2]
ymat = np.diag(y)
np.tile(ymat,z)

array([[4, 0, 0, 0, 4, 0, 0, 0],
       [0, 5, 0, 0, 0, 5, 0, 0],
       [0, 0, 6, 0, 0, 0, 6, 0],
       [0, 0, 0, 7, 0, 0, 0, 7]])

In [61]:
np.hstack([z,z*2,z*3])

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [66]:
ymat.argmax()

15

In [67]:
r=np.arange(36)

In [70]:
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [69]:
r[4,3:]

array([27, 28, 29])

In [75]:
test = np.random.randint(0,10,(4,4))
test

array([[5, 0, 4, 7],
       [7, 2, 3, 8],
       [9, 3, 3, 8],
       [8, 9, 4, 6]])

In [76]:
for i,row in enumerate(test):
    print(i,row)

0 [5 0 4 7]
1 [7 2 3 8]
2 [9 3 3 8]
3 [8 9 4 6]
